### PR TITLE
adding file

### PR DESCRIPTION
**Pull request by lucasprice**

### CODE REVIEW

**Comment by lucasprice** [comment]
I created a new branch. Or shld i be using Master branch?

**Comment by lucasprice** [comment]
I tried again, using a new branch that I created, "LucasP". See if it
works.

**Comment by nicolasbock** [comment]
> I created a new branch. Or shld i be using Master branch?

No, the idea is that we give everybody the chance to review proposed changes before we put those changes into the master branch. We want to keep the code in the master branch as good as possible, and by reviewing we can eliminate some issues before we put them into master.

**Comment by nicolasbock** [comment]
See my comment in #22

**Comment by nicolasbock** [comment]
Thanks!

**Pull request closed without merging**
