### PR TITLE
Debug

### PR DESCRIPTION
**Pull request by nicolasbock**

### CODE REVIEW

**Comment by togibson** [comment]
Sure


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Nicolas Bock <notifications@github.com> Date: 10/19/18  10:27 AM  (GMT-07:00) To: video-game-coding-club/geometry-smash <geometry-smash@noreply.github.com> Cc: togibson <gibson.travis@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [video-game-coding-club/geometry-smash] Debug (#185) 
@togibson Could you have a look at this too?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/video-game-coding-club/geometry-smash","title":"video-game-coding-club/geometry-smash","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/video-game-coding-club/geometry-smash"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nicolasbock in #185: @togibson Could you have a look at this too?"}],"action":{"name":"View Pull Request","url":"https://github.com/video-game-coding-club/geometry-smash/pull/185#issuecomment-431420821"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/video-game-coding-club/geometry-smash/pull/185#issuecomment-431420821",
"url": "https://github.com/video-game-coding-club/geometry-smash/pull/185#issuecomment-431420821",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [video-game-coding-club/geometry-smash] Debug (#185)",
"sections": [
{
"text": "",
"activityTitle": "**Nicolas Bock**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@nicolasbock",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"video-game-coding-club/geometry-smash\",\n\"issueId\": 185,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"video-game-coding-club/geometry-smash\",\n\"pullRequestId\": 185\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/video-game-coding-club/geometry-smash/pull/185#issuecomment-431420821"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 398531974\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by nicolasbock** [comment]
@togibson I'll merge this and the features we talked about earlier.

**Comment by togibson** [comment]
Love the updates for debugging. What do you think about adding a place for
the coordinates of the approaching obstacle so we could compare to the
coordinates of the hero?

**Comment by nicolasbock** [comment]
Maybe something like #186 ?

**Pull request merged**
