### PR TITLE
Simplify level design

### PR DESCRIPTION
**Pull request by nicolasbock**
Instead of using indices to pick the obstacle this change uses the
obstacle function name directly to simplify the code.

### CODE REVIEW

**Comment by nicolasbock** [comment]
Please have a look and leave comments! :smile:

**Comment by lucasprice** [comment]
Looks good to me. Just to clarify, the statement in the code:

obstacles[i][0](-time + position, floorHeight);

Is it just taking the ith item from the list, then the [0] index points to the obstacle name, which we pass the (x,y) coordinates for the obstacle function?

**Comment by nicolasbock** [comment]
Yes exactly. When you are happy with the change, could add a review and "approve" the pull request? Thanks!

**Comment by lucasprice** [comment]
How do we get this merged with the main branch? I don't have authorization...

**Comment by nicolasbock** [comment]
You can't merge it, I will do it :smile:

**Pull request merged**
